# Generated by Django 2.2.4 on 2021-02-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_auto_20210223_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Description',
            new_name='description',
        ),
    ]
